import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";



const baloo = localFont({
  src: "../../public/fonts/Baloo2-ExtraBold.ttf",
  variable: "--font-baloo",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="ko" className={baloo.variable}>
      <body>{children}</body>
    </html>
  );
}
