import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const baloo = localFont({
  src: "../../public/fonts/Baloo2-ExtraBold.ttf",
  variable: "--font-baloo",
  display: "swap",
});

const pretendard = localFont({
  src: "../../node_modules/pretendard/dist/web/variable/woff2/PretendardVariable.woff2",
  variable: "--font-pretendard",
  weight: "45 920",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="ko"
      className={`h-full ${baloo.variable} ${pretendard.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
